# Site settings
title: Sax Au Fond
email: your-email@domain.com
url: https://awwerbro.github.io/kwartet_site
#url: localhost:4000
description: Harelbeeks saxofoonkwartet

# Footer settings
footer: Andreas Werbrouck

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

gems:
